[env]
platform = espressif32
framework = arduino
lib_deps =
	m5stack/M5Unified@^0.2.17

[env:m5stick-c]
board = m5stick-c

[env:m5stick-s3]
board = esp32-s3-devkitc-1

[env:m5stack-cores3]
board = m5stack-cores3
